@id = 748e3dc9-224e-44d3-a345-1dd67e494e83

PUT http://localhost:5062/api/items/{{id}} HTTP/1.1
Content-Type: application/json

{
    "name": "Apple",
    "description": "Repels doctors for a 24 hour period after consumption",
    "price": 5
}