@id = 75c8548d-173f-457d-aa36-6537655a8902

PUT http://localhost:5062/api/items/{{id}} HTTP/1.1
Content-Type: application/json

{
    "name": "Apple",
    "description": "Repels doctors for a 24 hour period after consumption",
    "price": 5
}